#!/bin/bash

# Butter installation script

set -e

BUTTER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "🧈 Installing Butter..."
echo

# Make scripts executable
chmod +x "$BUTTER_DIR/bin/butter"

# Check dependencies
echo "Checking dependencies..."

missing_deps=""

# Core dependencies
command -v bash >/dev/null 2>&1 || missing_deps="$missing_deps bash"

# Optional but recommended
optional_deps=""
command -v fzf >/dev/null 2>&1 || optional_deps="$optional_deps fzf"
command -v xclip >/dev/null 2>&1 && command -v wl-copy >/dev/null 2>&1 || optional_deps="$optional_deps xclip/wl-clipboard"

if [ -n "$missing_deps" ]; then
    echo "❌ Missing required dependencies:$missing_deps"
    echo "Please install them and run this script again."
    exit 1
fi

if [ -n "$optional_deps" ]; then
    echo "⚠️  Optional dependencies not found:$optional_deps"
    echo "   Some features may not work without these."
    echo
fi

# Configure notes location
echo "📁 Where should your notes be stored?"
echo
echo "1) ~/Documents/ButterNotes/  (Recommended for mobile sync)"
echo "2) ~/notes/                   (Simple local storage)"
echo "3) ~/Nextcloud/Notes/         (Nextcloud sync)"
echo "4) ~/Dropbox/Notes/           (Dropbox sync)"
echo "5) Custom location"
echo
read -p "Choose [1-5] (default: 1): " choice

case "${choice:-1}" in
    1)
        NOTES_DIR="$HOME/Documents/ButterNotes"
        ;;
    2)
        NOTES_DIR="$HOME/notes"
        ;;
    3)
        NOTES_DIR="$HOME/Nextcloud/Notes"
        ;;
    4)
        NOTES_DIR="$HOME/Dropbox/Notes"
        ;;
    5)
        read -p "Enter custom path: " NOTES_DIR
        # Expand tilde if present
        NOTES_DIR="${NOTES_DIR/#\~/$HOME}"
        ;;
    *)
        NOTES_DIR="$HOME/Documents/ButterNotes"
        ;;
esac

echo
echo "📝 Notes will be stored in: $NOTES_DIR"

# Check for existing notes to migrate
echo
if [ -f "$HOME/.notes" ] || [ -f "$HOME/.tasks" ]; then
    echo "📦 Found existing notes/todos. They will be migrated on first use."
fi

# Create config file
CONFIG_FILE="$BUTTER_DIR/config/butter.conf"
cat > "$CONFIG_FILE" << EOF
#!/bin/bash
# Butter Configuration
# Generated by install.sh on $(date)

# Notes directory - change this to sync with mobile apps
BUTTER_NOTES_DIR="$NOTES_DIR"

# File names with .md extension for mobile compatibility
NOTES_FILE="\$BUTTER_NOTES_DIR/notes.md"
TODOS_FILE="\$BUTTER_NOTES_DIR/todos.md"

# Legacy paths (for migration)
LEGACY_NOTES_FILE="\$HOME/.notes"
LEGACY_TODOS_FILE="\$HOME/.tasks"

# Editor preference
BUTTER_EDITOR="\${BUTTER_EDITOR:-\${EDITOR:-nvim}}"

# Create notes directory if it doesn't exist
mkdir -p "\$BUTTER_NOTES_DIR"
EOF

echo "✅ Configuration saved to $CONFIG_FILE"

# Ask about shell integration
echo
echo "🐚 Add Butter to your shell?"
echo "This will add aliases and PATH to your shell config."
echo
read -p "Add to shell? [Y/n]: " add_shell

if [[ "${add_shell,,}" != "n" ]]; then
    # Detect shell config file
    if [ -f "$HOME/.config/bash/aliases" ]; then
        SHELL_CONFIG="$HOME/.config/bash/aliases"
    elif [ -f "$HOME/.bashrc" ]; then
        SHELL_CONFIG="$HOME/.bashrc"
    elif [ -f "$HOME/.zshrc" ]; then
        SHELL_CONFIG="$HOME/.zshrc"
    else
        SHELL_CONFIG="$HOME/.bashrc"
    fi
    
    # Check if already added
    if grep -q "# Butter - Note and todo management" "$SHELL_CONFIG" 2>/dev/null; then
        echo "⚠️  Butter already in $SHELL_CONFIG, updating aliases..."
        # Remove old entries
        sed -i '/# Butter - Note and todo management/,/^$/d' "$SHELL_CONFIG"
    fi
    
    # Add updated configuration
    echo "" >> "$SHELL_CONFIG"
    echo "# Butter - Note and todo management" >> "$SHELL_CONFIG"
    echo "export PATH=\"$BUTTER_DIR/bin:\$PATH\"" >> "$SHELL_CONFIG"
    echo "alias b='butter'" >> "$SHELL_CONFIG"
    echo "alias bc='butter clip'" >> "$SHELL_CONFIG"
    echo "alias bt='butter todo'" >> "$SHELL_CONFIG"
    echo "✅ Added to $SHELL_CONFIG"
fi

echo
echo "✅ Installation complete!"
echo
echo "📚 Quick start:"
echo "  1. Reload your shell: source $SHELL_CONFIG"
echo "  2. Try: b    (interactive mode)"
echo "  3. Add a note: butter \"My first note\""
echo "  4. Save clipboard: bc"
echo "  5. Add a todo: bt \"Fix the thing\""
echo "  6. Interactive selection: butter project    (uses fzf if available)"
echo
echo "Notes location: $NOTES_DIR"
echo "Config file: $CONFIG_FILE"